{
 "title": "PgBouncer",
 "description": "A visual representation of Prometheus metrics collected from PgBouncer servers.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(pgbouncer_up, instance)"
   },
   {
    "name": "port",
    "query": "label_values(pgbouncer_up, instance)"
   },
   {
    "name": "db",
    "label": "Db",
    "query": "label_values(pgbouncer_databases_current_connections,database)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(pgbouncer_up, service)"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "The pgbouncer version info",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pgbouncer_version_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Config max client connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_config_max_client_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stats queries total $db",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( sum (pgbouncer_stats_queries_pooled_total{database=~\"$db\"} ) )"
    }
   ]
  },
  {
   "title": "Database pool size.",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum (pgbouncer_databases_pool_size{database=~\"$db\"})",
     "legendFormat": "{{database}},{{service}}"
    }
   ]
  },
  {
   "title": "Count of used servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "pgbouncer_used_servers", "legendFormat": "Count of used servers" }
   ]
  },
  {
   "title": "Count of used clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "pgbouncer_used_clients", "legendFormat": "Used clients" }
   ]
  },
  {
   "title": "Count of free servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "pgbouncer_free_servers", "legendFormat": "Count of free servers" }
   ]
  },
  {
   "title": "Count of free clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "pgbouncer_free_clients", "legendFormat": "Free clients" }
   ]
  },
  {
   "title": "Current number of connections for this database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "pgbouncer_databases_current_connections{database=\"$db\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Client active connections $db",
   "type": "timeseries",
   "description": "Client connections linked to server connection and able to process queries, shown as connection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=~\"$db\"})",
     "legendFormat": "Conncetions"
    }
   ]
  },
  {
   "title": "Pools Connections",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{database=~\"$db\"}",
     "legendFormat": "Client active connections "
    },
    {
     "expr": "pgbouncer_pools_client_waiting_connections{database=~\"$db\"}",
     "legendFormat": "Client waiting connections"
    },
    {
     "expr": "pgbouncer_pools_server_active_connections{database=~\"$db\"}",
     "legendFormat": "Server active connections"
    },
    {
     "expr": "pgbouncer_pools_server_idle_connections{database=~\"$db\"}",
     "legendFormat": "Server idle connections"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{database=~\"$db\"}",
     "legendFormat": "Server used connections"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{database=~\"$db\"}",
     "legendFormat": "Server testing connections"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{database=~\"$db\"}",
     "legendFormat": "Server login connections"
    },
    {
     "expr": "pgbouncer_databases_current_connections{database=~\"$db\"}",
     "legendFormat": "Database current connections"
    }
   ]
  },
  {
   "title": "Total Query Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_queries_duration_seconds_total{database=\"$db\"}[30m]) ) )",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total of incoming / outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_received_bytes_total{database=~\"$db\"}[30m])*8 ) )",
     "legendFormat": "Received bytes total"
    },
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_sent_bytes_total{database=~\"$db\"}[30m])*8 ) )",
     "legendFormat": "Sent bytes total"
    }
   ]
  },
  {
   "title": "Transactions stats",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_server_in_transaction_seconds{database=~\"$db\"}[30m]) ) )  ",
     "legendFormat": "Transactions duration microseconds"
    },
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_sql_transactions_pooled_total{database=~\"$db\"}[30m]) ) )",
     "legendFormat": "Transactions total"
    }
   ]
  },
  {
   "title": "Age of oldest unserved client connection, shown as second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_queries_duration_seconds_total{database=~\"$db\"}[30m]) ) )",
     "legendFormat": "Duration microseconds"
    },
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_pools_client_maxwait_seconds{database=~\"$db\"}[30m]) ) ) ",
     "legendFormat": "Waiting duration microseconds"
    }
   ]
  },
  {
   "title": "Count of clients in login state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgbouncer_login_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Count of pools",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgbouncer_pools", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Databases reserve pool size.",
   "type": "barchart",
   "description": "Maximum number of additional connections for this database",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 61 },
   "targets": [
    {
     "expr": "sum (rate(pgbouncer_databases_reserve_pool{database=~\"$db\"}[30m]))",
     "legendFormat": "{{database}},{{service}}"
    }
   ]
  }
 ]
}